"""add b2b and b2c availability flags to product

Revision ID: 033e228a0348
Revises: 7aee7bef2fed
Create Date: 2026-06-10 13:58:39.239454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033e228a0348'
down_revision: Union[str, Sequence[str], None] = '7aee7bef2fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('b2b_available', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('b2c_available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'b2c_available')
    op.drop_column('products', 'b2b_available')
    # ### end Alembic commands ###
