"""replace b2b and b2c flags with is_b2b_only

Revision ID: 10aa7f780fef
Revises: 3009b7d53ca6
Create Date: 2026-06-19 15:37:42.712106

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10aa7f780fef"
down_revision: Union[str, Sequence[str], None] = "3009b7d53ca6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "is_b2b_only", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.drop_column("products", "b2c_available")
    op.drop_column("products", "b2b_available")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("b2b_available", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("b2c_available", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("products", "is_b2b_only")
    # ### end Alembic commands ###
