"""add_slug_to_category_add_slug_and_image_url_to_product

Revision ID: 3009b7d53ca6
Revises: d875bdd596d5
Create Date: 2026-06-17 15:18:08.239285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3009b7d53ca6'
down_revision: Union[str, Sequence[str], None] = 'd875bdd596d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.add_column('products', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('products', sa.Column('main_image_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_column('products', 'main_image_url')
    op.drop_column('products', 'slug')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
