"""unique cart_items user+product

Revision ID: 3bd88158c580
Revises: 89200825e36f
Create Date: 2026-06-29 14:48:14.691341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd88158c580'
down_revision: Union[str, Sequence[str], None] = '89200825e36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cart_user_product', 'cart_items', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cart_user_product', 'cart_items', type_='unique')
    # ### end Alembic commands ###
