"""add company_id to addresses and nullable user_id

Revision ID: 5a04df09ad1b
Revises: 3bd88158c580
Create Date: 2026-06-30 16:08:52.157435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a04df09ad1b'
down_revision: Union[str, Sequence[str], None] = '3bd88158c580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('company_id', sa.Uuid(), nullable=True))
    op.alter_column('addresses', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('addresses_user_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'addresses', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint(
        'ck_address_owner',
        'addresses',
        "(user_id IS NOT NULL)::int + (company_id IS NOT NULL)::int = 1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_address_owner', 'addresses', type_='check')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key(op.f('addresses_user_id_fkey'), 'addresses', 'users', ['user_id'], ['id'])
    op.alter_column('addresses', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('addresses', 'company_id')
    # ### end Alembic commands ###
