"""add_snapshots_constraints_and_contact_fields

Revision ID: 7ca949d8067c
Revises: 033e228a0348
Create Date: 2026-06-10 15:31:21.243621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca949d8067c'
down_revision: Union[str, Sequence[str], None] = '033e228a0348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('order_items', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('order_items', sa.Column('product_name', sa.String(length=255), nullable=False))
    op.add_column('order_items', sa.Column('product_sku', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('shipping_street', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('shipping_country', sa.String(length=100), nullable=False))
    op.create_unique_constraint('uq_product_volume_discount', 'product_volume_discounts', ['product_id', 'min_quantity'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_volume_discount', 'product_volume_discounts', type_='unique')
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_street')
    op.drop_column('order_items', 'product_sku')
    op.drop_column('order_items', 'product_name')
    op.drop_column('order_items', 'discount_percentage')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'address')
    op.drop_table('addresses')
    # ### end Alembic commands ###
