"""add company_joined_at to users

Revision ID: 89200825e36f
Revises: 10aa7f780fef
Create Date: 2026-06-29 12:55:30.948211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89200825e36f'
down_revision: Union[str, Sequence[str], None] = '10aa7f780fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_joined_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_joined_at')
    # ### end Alembic commands ###
