"""add company active flag and set null on delete for user company id

Revision ID: b1f7e8a2d493
Revises: 7ca949d8067c
Create Date: 2026-06-10 16:57:15.568685

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1f7e8a2d493"
down_revision: Union[str, Sequence[str], None] = "7ca949d8067c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.drop_constraint(op.f("users_company_id_fkey"), "users", type_="foreignkey")
    op.create_foreign_key(
        None, "users", "companies", ["company_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_company_id_fkey"), "users", "companies", ["company_id"], ["id"]
    )
    op.drop_column("companies", "is_active")
    # ### end Alembic commands ###
