"""billing_document address_type remove_company_address

Revision ID: c08b7b1b873e
Revises: 5a04df09ad1b
Create Date: 2026-07-01 11:23:49.388500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08b7b1b873e'
down_revision: Union[str, Sequence[str], None] = '5a04df09ad1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    addresstype = sa.Enum('SHIPPING', 'BILLING', name='addresstype')
    addresstype.create(op.get_bind())
    op.create_table('billing_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('RECEIPT', 'PERSONAL_INVOICE', 'COMPANY_INVOICE', name='documenttype'), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_nip', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('billing_street', sa.String(length=255), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_postal_code', sa.String(length=20), nullable=True),
    sa.Column('billing_country', sa.String(length=100), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number'),
    sa.UniqueConstraint('order_id')
    )
    op.add_column('addresses', sa.Column(
        'address_type',
        sa.Enum('SHIPPING', 'BILLING', name='addresstype'),
        nullable=False,
        server_default='SHIPPING',
    ))
    op.alter_column('addresses', 'address_type', server_default=None)
    op.create_index(
        'ix_addresses_company_billing',
        'addresses',
        ['company_id'],
        unique=True,
        postgresql_where="address_type='BILLING'",
    )
    op.drop_column('companies', 'address')
    op.drop_column('orders', 'billing_company_name')
    op.drop_column('orders', 'billing_nip')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('billing_nip', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('billing_company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('ix_addresses_company_billing', table_name='addresses')
    op.drop_column('addresses', 'address_type')
    op.drop_table('billing_documents')
    sa.Enum(name='addresstype').drop(op.get_bind())
    # ### end Alembic commands ###
